"""Allow same email for patients per doctor

Revision ID: 9bfa147c3cae
Revises: b9438452406e
Create Date: 2025-07-30 11:29:43.237073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfa147c3cae'
down_revision = 'b9438452406e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patients_email_key'), type_='unique')
        batch_op.create_unique_constraint('unique_patient_email_per_doctor', ['email', 'doctor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('unique_patient_email_per_doctor', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('patients_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
